param(
    [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
)

$ErrorActionPreference = 'Stop'
$PSDefaultParameterValues['*:Encoding'] = 'utf8'
[Console]::InputEncoding = [System.Text.Encoding]::UTF8
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

Set-Location -LiteralPath $Root

function Read-IfExists {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,
        [int]$MaxChars = 12000
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        return "[missing: $Path]"
    }

    $text = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
    if ($text.Length -le $MaxChars) {
        return $text.Trim()
    }

    return ($text.Substring(0, $MaxChars) + "`n`n[truncated by compact hook: $Path]").Trim()
}

function Run-Git {
    param([string[]]$GitArgs)

    try {
        $output = & git @GitArgs 2>&1
        if ($LASTEXITCODE -ne 0) {
            return ($output | Out-String).Trim()
        }
        return ($output | Out-String).Trim()
    } catch {
        return "[git unavailable: $($_.Exception.Message)]"
    }
}

$generatedAt = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss zzz")
$gitLog = Run-Git -GitArgs @('log', '--oneline', '--decorate', '-10')
$gitStatus = Run-Git -GitArgs @('status', '--short')
$trackedPlans = @(
    'CONCEPT_EXTENSION_IMPLEMENTATION_PLAN.md',
    'ORCHESTRATION_PLAN.md',
    'AGENT_PROGRESS_LOG.md'
)

$conceptPlan = Read-IfExists 'CONCEPT_EXTENSION_IMPLEMENTATION_PLAN.md' 10000
$orchestrationPlan = Read-IfExists 'ORCHESTRATION_PLAN.md' 9000
$progressLog = Read-IfExists 'AGENT_PROGRESS_LOG.md' 9000

$content = @"
# MemoryX Orchestrator Compact Context

Generated: $generatedAt
Root: $Root

This file is auto-generated by `.codex/hooks/refresh_orchestrator_context.ps1`.
It is the first file to read after Codex session start or context compact.

## Role

You are the MemoryX Orchestrator.

Primary objective:

- finish MemoryX according to the concept without losing the features that make it different from RAG/vector DB systems.

## Mandatory Full Sources

Read these when detailed implementation work starts:

- CONCEPT_EXTENSION_IMPLEMENTATION_PLAN.md
- ORCHESTRATION_PLAN.md
- AGENT_PROGRESS_LOG.md
- Concept/Russian extension file when concept details are disputed

## Non-Regression Contract

Never remove, bypass, or weaken:

- knowledge atoms instead of text chunks;
- contexts, branches, conflicts, `CTX_PROBE`, self-consistency;
- heptapod backward+forward reasoning;
- `FixedPointSolver` fixed-point answer assembly;
- minimal proof `AnswerGraph`;
- federation based on claims/provenance/metadata;
- CAS integrity, Merkle/integrity verification, CRDT, WAL/snapshot, repair/rebuild;
- full MCP database operation surface;
- project/user scoped local-first storage;
- portable CPU build default.

## Model Routing

- `gpt-5.4-mini`: default for routine coding, tests, docs, MCP examples, clippy/fmt.
- `gpt-5.4`: integration across solver/store/CAS/federation/MCP write paths.
- `gpt-5.5`: architecture gates, safety review, release audit only.

## Current Git Log

~~~text
$gitLog
~~~

## Current Git Status

~~~text
$gitStatus
~~~

## Progress Log

~~~markdown
$progressLog
~~~

## Implementation Plan Compact Extract

~~~markdown
$conceptPlan
~~~

## Orchestration Plan Compact Extract

~~~markdown
$orchestrationPlan
~~~

## Immediate Operating Rules After Compact

1. Do not ask the user to resend context.
2. Read this file first.
3. If this file is stale, run:
   pwsh -NoLogo -ExecutionPolicy Bypass -File .codex/hooks/refresh_orchestrator_context.ps1
4. Preserve dirty user changes. Do not revert them.
5. Before implementation, inspect real files touched by the task.
6. After meaningful work, append a concise entry to AGENT_PROGRESS_LOG.md.
7. Keep commits narrow and local unless the user asks to publish.

"@

Set-Content -LiteralPath 'ORCHESTRATOR_CONTEXT_COMPACT.md' -Value $content -Encoding UTF8
Write-Output "Updated ORCHESTRATOR_CONTEXT_COMPACT.md"
